// Package order provides generic ordering types for database queries.
//
// [Order] is parameterized by a field type (typically a generated byte enum)
// and a [Direction] (Asc or Desc):
//
//	order.Order[UserField]{
//	    Field:     UserFieldName,
//	    Direction: order.Asc,
//	}
package order
